"""Deterministic terminal, JSON, and Markdown audit reports."""

from __future__ import annotations

import json
from typing import Any

from seedbox_doctor.models import AuditReport, Finding, Status


_LABELS = {
    Status.PASS: "PASS",
    Status.WARN: "WARN",
    Status.FAIL: "FAIL",
    Status.SKIP: "SKIP",
}


def _finding_dict(finding: Finding) -> dict[str, Any]:
    return {
        "check_id": finding.check_id,
        "status": finding.status.value,
        "summary": finding.summary,
        "evidence": list(finding.evidence),
        "remediation": finding.remediation,
        "metadata": dict(finding.metadata),
    }


def report_dict(report: AuditReport) -> dict[str, Any]:
    """Return the stable public report schema."""

    return {
        "schema_version": report.schema_version,
        "generated_at": report.generated_at.isoformat(),
        "instance": report.instance,
        "score": report.score,
        "status": report.worst_status.value,
        "counts": {
            status.value: report.counts[status]
            for status in (Status.PASS, Status.WARN, Status.FAIL, Status.SKIP)
        },
        "findings": [_finding_dict(finding) for finding in report.findings],
    }


def render_json(report: AuditReport, *, indent: int | None = 2) -> str:
    """Render UTF-8-safe JSON suitable for automation."""

    return json.dumps(
        report_dict(report),
        indent=indent,
        ensure_ascii=False,
        sort_keys=True,
    ) + "\n"


def render_text(report: AuditReport) -> str:
    """Render a compact terminal report without ANSI control sequences."""

    counts = report.counts
    lines = [
        f"seedbox-doctor — {report.instance}",
        f"Score: {report.score}/100 | Status: {_LABELS[report.worst_status]}",
        (
            "Results: "
            f"{counts[Status.PASS]} pass, {counts[Status.WARN]} warn, "
            f"{counts[Status.FAIL]} fail, {counts[Status.SKIP]} skip"
        ),
        "",
    ]
    for finding in report.findings:
        lines.append(
            f"{_LABELS[finding.status]:4}  {finding.check_id:28}  {finding.summary}"
        )
        for evidence in finding.evidence:
            lines.append(f"      evidence: {evidence}")
        if finding.remediation:
            lines.append(f"      fix: {finding.remediation}")
    return "\n".join(lines) + "\n"


def _escape_markdown(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def render_markdown(report: AuditReport) -> str:
    """Render a support-friendly Markdown report."""

    lines = [
        "# seedbox-doctor report",
        "",
        f"- Instance: `{_escape_markdown(report.instance)}`",
        f"- Generated: `{report.generated_at.isoformat()}`",
        f"- Score: **{report.score}/100**",
        f"- Overall status: **{_LABELS[report.worst_status]}**",
        "",
        "| Status | Check | Summary |",
        "| --- | --- | --- |",
    ]
    for finding in report.findings:
        lines.append(
            "| "
            f"{_LABELS[finding.status]} | `{_escape_markdown(finding.check_id)}` | "
            f"{_escape_markdown(finding.summary)} |"
        )

    remediation = [finding for finding in report.findings if finding.remediation]
    if remediation:
        lines.extend(["", "## Suggested actions", ""])
        for finding in remediation:
            lines.append(
                f"- **`{_escape_markdown(finding.check_id)}`:** "
                f"{_escape_markdown(finding.remediation or '')}"
            )

    lines.extend(
        [
            "",
            "_Generated by [seedbox-doctor](https://github.com/SAGIRIxr/seedbox-doctor). "
            "The default report omits torrent names, hashes, tracker URLs, and credentials._",
            "",
        ]
    )
    return "\n".join(lines)

